import { company } from "../site.js";
const date = "6 ottobre 2026";
// TODO_PRIVACY_REVIEW: prima del go-live il titolare deve approvare testo, basi giuridiche,
// tempi di conservazione operativi, DPA/sub-responsabili, regioni e garanzie dei trasferimenti.
// Verificare le impostazioni reali di Vercel, Resend, Upstash e della casella aziendale.
const privacy = `
<h2>1. Titolare e contatti</h2>
<p>Il titolare del trattamento è ${company.legalName}, P. IVA ${company.vat}, con sede in ${company.street}, ${company.postalCode} ${company.city} (${company.province}), Italia. Per informazioni o per esercitare i tuoi diritti puoi scrivere a <a href="mailto:${company.email}">${company.email}</a> o inviare una comunicazione alla sede.</p>
<h2>2. Dati trattati</h2>
<p>Il modulo contatti raccoglie nome, email, telefono facoltativo, tipo di richiesta e messaggio. Ti chiediamo di non inserire dati particolari, come informazioni sulla salute, documenti d’identità o dati di altre persone non necessari alla richiesta. I dati obbligatori servono a comprendere la richiesta e a risponderti; senza di essi non è possibile inviare il modulo. Puoi comunque contattarci telefonicamente o via email.</p>
<p>Durante la navigazione, l’infrastruttura di hosting può trattare dati tecnici quali indirizzo IP, data e ora, indirizzo della risorsa richiesta, informazioni sul browser e codici di risposta. Per limitare gli abusi del modulo viene utilizzato un identificatore ottenuto dall’indirizzo IP tramite una funzione crittografica con chiave segreta, insieme a un contatore temporaneo.</p>
<h2>3. Finalità e basi giuridiche</h2>
<ul><li>Gestire richieste di preventivo e informazioni relative ai servizi: esecuzione di misure precontrattuali su richiesta dell’interessato, ai sensi dell’art. 6, par. 1, lett. b) GDPR.</li><li>Gestire altre comunicazioni pertinenti all’attività: legittimo interesse del titolare a mantenere i rapporti con gli interlocutori, art. 6, par. 1, lett. f), valutato nel rispetto dei loro diritti.</li><li>Garantire disponibilità e sicurezza del sito e prevenire spam e abusi: legittimo interesse alla protezione dei sistemi, art. 6, par. 1, lett. f).</li><li>Adempiere a obblighi normativi e gestire eventuali controversie: obbligo legale, art. 6, par. 1, lett. c), o legittimo interesse alla tutela dei diritti.</li><li>Caricare la mappa Google Maps facoltativa: consenso espresso attraverso il pulsante di attivazione, revocabile dalla stessa pagina, art. 6, par. 1, lett. a).</li></ul>
<p>Non utilizziamo il modulo per newsletter o marketing e non prendiamo decisioni automatizzate con effetti giuridici sull’interessato.</p>
<h2>4. Modalità e sicurezza</h2>
<p>I dati sono trattati con strumenti informatici e accessi limitati alle persone autorizzate. Il sito utilizza HTTPS, controlli sui campi e misure antispam. I messaggi vengono inoltrati alla casella aziendale; l’applicazione non crea un archivio dei messaggi in un proprio database e non inserisce il contenuto, l’email o il telefono nei propri log applicativi. Nessuna trasmissione o conservazione informatica può essere garantita come priva di ogni rischio.</p>
<h2>5. Destinatari e fornitori</h2>
<p>Possono accedere ai dati il personale autorizzato e i fornitori necessari al funzionamento del servizio, nei limiti delle rispettive attività: Vercel per l’hosting e l’esecuzione del modulo, Resend per l’invio delle email, Upstash per i contatori antispam e il fornitore della casella email aziendale. I messaggi possono essere comunicati ad autorità o consulenti quando necessario per obblighi di legge o tutela dei diritti. I dati non sono diffusi.</p>
<p>Google riceve dati di navigazione solo se scegli di attivare la mappa incorporata. Il servizio è regolato anche dall’<a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">informativa Google</a>. I link esterni aprono siti soggetti alle rispettive informative.</p>
<h2>6. Trasferimenti fuori dallo Spazio economico europeo</h2>
<p>I fornitori tecnologici possono operare anche al di fuori dello Spazio economico europeo. Gli eventuali trasferimenti devono essere coperti dalle garanzie previste dal capo V del GDPR, quali decisioni di adeguatezza applicabili o clausole contrattuali standard e, ove necessarie, misure supplementari. Puoi richiedere al titolare informazioni sulle garanzie applicabili al trattamento dei tuoi dati.</p>
<h2>7. Conservazione</h2>
<p>Le richieste e la relativa corrispondenza sono conservate per il tempo necessario a gestire il contatto e gli eventuali rapporti conseguenti. I documenti che assumono rilevanza contrattuale, fiscale o probatoria sono conservati per i termini previsti dalla normativa o necessari alla tutela dei diritti. I dati non più necessari devono essere eliminati secondo le procedure del titolare.</p>
<p>I contatori antispam dell’applicazione scadono dopo 10 minuti. I log tecnici e i dati gestiti dai fornitori seguono i tempi dei servizi e delle configurazioni adottate, limitati alle esigenze operative e di sicurezza. Puoi chiedere al titolare maggiori informazioni sui tempi applicabili alla tua richiesta.</p>
<h2>8. Diritti</h2>
<p>Nei casi previsti dagli artt. 15–22 GDPR puoi chiedere accesso, rettifica, cancellazione, limitazione e portabilità dei dati, nonché opporti ai trattamenti basati sul legittimo interesse. Puoi revocare il consenso alla mappa senza pregiudicare la liceità del trattamento precedente. Per esercitare i diritti usa i contatti del titolare; potremmo richiedere le informazioni strettamente necessarie per verificare l’identità.</p>
<p>Hai diritto di presentare reclamo al <a href="https://www.garanteprivacy.it/" target="_blank" rel="noopener noreferrer">Garante per la protezione dei dati personali</a> o all’autorità competente nel luogo di residenza, lavoro o presunta violazione.</p>
<h2>9. Cookie e aggiornamenti</h2>
<p>Consulta la <a href="/cookie-policy">Cookie Policy</a> per conoscere le tecnologie utilizzate e le modalità di attivazione e revoca della mappa. Questa informativa viene aggiornata quando cambiano i trattamenti o i servizi utilizzati.</p>`;
const cookies = `
<h2>1. Tecnologie presenti sul sito</h2>
<p>Il codice del sito non installa cookie propri, non usa localStorage o sessionStorage e non integra Google Analytics, pixel pubblicitari o altri strumenti di profilazione. I font e le immagini sono ospitati insieme al sito. Il modulo contatti invia i dati esclusivamente all’endpoint interno <code>/api/contact</code>.</p>
<p>L’infrastruttura Vercel può trattare dati tecnici necessari all’erogazione e alla sicurezza del servizio. Il limite antispam del modulo è gestito sul server tramite contatori temporanei Upstash; non legge né scrive informazioni sul dispositivo per riconoscere il visitatore.</p>
<h2>2. Mappa Google Maps: scelta facoltativa</h2>
<p>Nella pagina <a href="/dove-siamo">Dove siamo</a> la mappa è inizialmente bloccata: il browser non contatta Google Maps finché non premi “Acconsento e carico la mappa”. L’attivazione può comportare la trasmissione a Google di indirizzo IP e informazioni del browser, l’uso di cookie o altre tecnologie del fornitore e trasferimenti internazionali. Non è necessaria per consultare indirizzi e recapiti.</p>
<p>Il consenso vale solo per la pagina aperta e non viene salvato. Puoi disattivare la mappa con “Revoca consenso alla mappa” oppure ricaricando o lasciando la pagina. La revoca rimuove la mappa e impedisce ulteriori caricamenti dell’incorporamento; non cancella i dati già trasmessi né i cookie eventualmente impostati da Google, che puoi gestire nelle impostazioni del browser.</p>
<p>Per le tecnologie del fornitore, le relative finalità e durate consulta le <a href="https://policies.google.com/technologies/cookies" target="_blank" rel="noopener noreferrer">informazioni sui cookie Google</a> e la <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy Google</a>. Non fissiamo un elenco o durate non verificabili dei cookie del servizio, che possono variare secondo il browser e l’account Google.</p>
<h2>3. Link esterni</h2>
<p>I pulsanti “Indicazioni stradali” aprono Google Maps come sito esterno solo quando li selezioni. Il sito di destinazione applica le proprie condizioni e informative. I link telefonici ed email aprono l’applicazione scelta sul tuo dispositivo.</p>
<h2>4. Gestire le scelte</h2>
<p>Non viene mostrato un banner generale di accettazione: la scelta relativa alla sola mappa viene richiesta nel punto in cui il contenuto può essere caricato. Puoi consultare il sito senza attivarla. Le impostazioni del browser permettono inoltre di controllare, bloccare e cancellare i cookie dei servizi esterni.</p>
<h2>5. Contatti</h2>
<p>Il titolare è ${company.legalName}, ${company.street}, ${company.postalCode} ${company.city} (${company.province}), Italia. Scrivi a <a href="mailto:${company.email}">${company.email}</a> per domande e diritti. Maggiori dettagli sono nella <a href="/privacy">Privacy Policy</a>.</p>`;
export const Legal = (path) =>
  `<section class="location-hero legal-hero"><div class="location-container"><a class="location-back" href="/">← Torna alla home</a><p class="location-kicker">TRASPARENZA E DATI PERSONALI</p><h1>${path === "/privacy" ? "Privacy Policy" : "Cookie Policy"}</h1><p class="location-intro">Ultimo aggiornamento: ${date}</p></div></section><article class="legal-content location-container">${path === "/privacy" ? privacy : cookies}</article>`;
export const NotFound = () =>
  `<section class="location-hero"><div class="location-container"><p class="location-kicker">ERRORE 404</p><h1>Pagina non trovata</h1><p class="location-intro">La pagina potrebbe essere stata spostata oppure l’indirizzo non è corretto.</p><a class="location-call" href="/">Torna alla homepage</a></div></section>`;
